swagger: "2.0"
info:
  description: "This is a server Library server."
  version: "1.0.5"
  title: "Swagger LibraryManage"
tags:
- name: "books"
  description: "Everything about books in library"
- name: "users"
  description: "About User"
- name: "borrows"
  description: "Operations about info"

paths:
  /v1/books:
    post:
      tags:
      - "books"
      summary: "Add a new book "
      description: ""
      operationId: "addBook"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object that needs to be added to the table"
        required: true
      responses:
        "404":
          description: "Book not found"
        "400":
          description: "Bad request"
        "201":
          description: "data"
    put:
      tags:
      - "books"
      summary: "Update Book"
      description: ""
      operationId: "updateBook"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object that needs to be added to the table"
        required: true
      responses:
        "400":
          description: "Bad request"
        "201":
          description: "ok"

    get:
      tags:
      - "books"
      summary: "Search Book"
      description: ""
      operationId: "searchBook"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object to search"
        required: true
        responses:
          "404":
            description: "Book not found"
          "400":
            description: "Bad Request"

    delete:
      tags:
        - "books"
      summary: "Delete Book"
      description: ""
      operationId: "deleteBook"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object to delete"
        required: true
      responses:
        "200":
          description: "ok"
        "400":
          description: "Bad Request"

  /v1/borrows:
    post:
      tags:
        - "borrows"
      summary: "Add a new info "
      description: ""
      operationId: "addInfo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Info object that needs to be added to the table"
          required: true
      responses:
        "404":
          description: "Info not found"
        "400":
          description: "Bad request"
        "201":
          description: "data"
    put:
      tags:
        - "borrows"
      summary: "Update Info"
      description: ""
      operationId: "updateInfo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Info object that needs to be added to the table"
          required: true
      responses:
        "400":
          description: "Bad request"
        "201":
          description: "ok"

    get:
      tags:
        - "borrows"
      summary: "SearchInfo "
      description: ""
      operationId: "searchInfo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Info object to search"
          required: true
          responses:
            "404":
              description: "Info not found"
            "400":
              description: "Bad Request"
    delete:
      tags:
        - "borrows"
      summary: "Delete Info"
      description: ""
      operationId: "deleteInfo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Info object to delete"
          required: true
      responses:
        "200":
          description: "ok"
        "400":
          description: "Bad Request"



  /v1/users:
    post:
      tags:
        - "users"
      summary: "Add a new user "
      description: ""
      operationId: "addUser"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Users object that needs to be added to the table"
          required: true
      responses:
        "404":
          description: "User not found"
        "400":
          description: "Bad request"
        "201":
          description: "data"
    put:
      tags:
        - "users"
      summary: "Update User"
      description: ""
      operationId: "updateUser"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Users object that needs to be added to the table"
          required: true
      responses:
        "400":
          description: "Bad request"
        "201":
          description: "ok"

    get:
      tags:
        - "users"
      summary: "Search User"
      description: ""
      operationId: "search User"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Users object to search"
          required: true
          responses:
            "404":
              description: "User not found"
            "400":
              description: "Bad Request"

    delete:
      tags:
        - "users"
      summary: "Delete User"
      description: ""
      operationId: "deleteUser"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Users object to delete"
          required: true
      responses:
        "200":
          description: "ok"
        "400":
          description: "Bad Request"

  /v1/ticket/<id>:
    get:
      tags:
      - "ticket"
      summary: "Find ticket by ID"
      description: "Returns a single ticket"
      operationId: "getTicketById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "ticketId"
        in: "path"
        description: "ID to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Bad Request"
        "404":
          description: "Ticket not found"


  /v1/bookfilter?keyword=:
    get:
      tags:
      - "filters"
      summary: "SearchBook by Filter "
      description: ""
      operationId: "searchBookByFilter"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Book object to search"
        required: true
      responses:
        "404":
          description: "Book not found"
        "400":
          description: "Bad Request"

  /v1/userfilter?keyword=:
    get:
      tags:
      - "filters"
      summary: "SearchUser by Filter "
      description: ""
      operationId: "searchUserByFilter"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object to search"
        required: true
      responses:
        "404":
          description: "User not found"
        "400":
          description: "Bad Request"

  /v1/borrowfilter?keyword=:
    get:
      tags:
        - "filters"
      summary: "SearchInfo by Filter "
      description: ""
      operationId: "searchInfoByFilter"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Info object to search"
          required: true
      responses:
        "404":
          description: "Info not found"
        "400":
          description: "Bad Request"



definitions:
  Books:
    type: "object"
    properties:
      id_book:
        type: "integer"
      name:
        type: "string"
      types:
        type: "string"
      publisher:
        type: "integer"
      language:
        type: "string"
      author:
        type: "string"
  Users:
    type: "object"
    properties:
      id_name:
        type: "integer"
      name_user:
        type: "string"
      age:
        type: "integer"
      address:
        type: "string"
      phone:
        type: "string"
  Borrows:
    type: "object"
    properties:
      id:
        type: "integer"
      id_user:
        type: "integer"
      id_book:
        type: "integer"
      date:
        type: "datetime"
      price:
        type: "integer"
  Ticket:
    type: "object"
    properties:
      date:
        type: "datetime"
      name:
        type: "string"
      name_user:
        type: "string"
      price:
        type: "integer"
  UserFilter:
    type: "object"
    properties:
      id_name:
        type: "integer"
      name_user:
        type: "string"
      age:
        type: "integer"
      address:
        type: "string"
      phone:
        type: "string"
  BookFilter:
    type: "object"
    properties:
      id_book:
        type: "integer"
      name:
        type: "string"
      types:
        type: "string"
      publisher:
        type: "integer"
      language:
        type: "string"
      author:
        type: "string"
  BorrowFilter:
    type: "object"
    properties:
      date:
        type: "datetime"
      name_user:
        type: "string"
      name:
        type: "string"
      age:
        type: "integer"
      price:
        type: "integer"
